services:
  postgres:
    image: postgres
    container_name: container_postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PASSWORD_POSTGRES}
      POSTGRES_USER: ${USER_POSTGRES}
      POSTGRES_DB: ${DB_NAME}
    ports:
        - "5432:5432"
